[api_keys]
OPENAI_KEY = "sk-SX9zeWusVCPndt9SKPx2iDHBWjE-d44V3dlsxHO9ErT3BlbkFJx0eEgu26DA1c2YdEnHmuJ_cSWJAN10vluvvaS0puYA"
GEMINI_KEY = "AIzaSyCcMZPrzP5me7Rl4pmAc1Nn5vUDSan5Q6E"
PERPLEXITY_KEY = "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"
