OPENAI_KEY = "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"
GEMINI_KEY = "AIzaSyCcMZPrzP5me7Rl4pmAc1Nn5vUDSan5Q6E"
PERPLEXITY_KEY = "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"
